### ISSUE TITLE
"Unit" documentation

### ISSUE THREAD

**Issue by idkjs** [reasonml/reasonml.github.io#180]
Suggested definition, as I understand it.
```
# Unit
"unit" is a single value like 0 or "hello". It's created by typing an empty set of parentheses (). Unit/() has nothing to do with function call syntax () in Javascript. "unit" is also a type - like int, string, etc.
```

**Comment by yawaramin** [comment]
See also https://reasonml.github.io/guide/language/function/#no-argument

**Comment by ddeath** [comment]
I also vote for updating the docs. I personally would add section "Build in types" or something like that where would be all types of string, int and of course unit.

I got frustrated because I had following code:
```
let component = ReasonReact.reducerComponent("App");

let make = _children => {
  ...component,
  render: (self) =>
    <div>
      <input name="search" />
      <button>ReasonReact.string('Search')</button>
    </div>,
};
```

and it complained in vscode that self is unused. So my next step as I am coming from es6, react word to rewrite it:

```
let component = ReasonReact.reducerComponent("App");

let make = _children => {
  ...component,
  render: () =>
    <div>
      <input name="search" />
      <button>ReasonReact.string('Search')</button>
    </div>,
};
```

But instead of solving a problem I got:
```
Error: This pattern matches values of type unit
       but a pattern was expected which matches values of type
         ReasonReact.self('a, 'b, 'c)
ReasonReact.self(state, ReasonReact.noRetainedProps, action)
```
So my next step was open the docs and take a look at unit type. There is none in the left menu, so I clicked on Type! => no mention on that page

Also when you search `unit` in the search bar it does not bring results which would seem like what you are searching for.
![search](https://user-images.githubusercontent.com/2537379/40973716-8b1282fe-68c5-11e8-87fb-e0210c2a6777.png)

Also it is strange that:
```
let logSomething = () => {
  print_endline("hello");
  print_endline("world")
};
```
is ok, but:
```
let logSomething = 25 => {
  print_endline("hello");
  print_endline("world")
};
```

will throw an error. 25 is value and () is value too, so it is strange that one is working and another no.

**Comment by yawaramin** [comment]
About the last question, the reason is that raw literals in function parameter patterns need 'protection'; it's a syntax requirement to avoid ambiguity. You can make it work like: `let logSomething = (25) => ...;`

For `()`, that's already unambiguous, so it works.

**Comment by kyldvs** [comment]
Unit has been added to the new overview page: https://reasonml.github.io/docs/en/overview#unit

There is also a section on built in types now as @ddeath suggests https://reasonml.github.io/docs/en/overview#built-in-types
