### ISSUE TITLE
Sharable Try links

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#43]
We can encode the snippet in the URL in the simple case

**Comment by chidelmun** [comment]
I have developed a  standalone prototype  for generating the Tryit  links
and it's found on my :  [Heroku Account here ](https://reasonml.herokuapp.com/)

How ever, I'm unable to setup the project locally due to plugins error below 

`Delveris-MacBook-Air:reasonml.github.io delverichick$ npm install
npm WARN deprecated glamor-inline@1.0.5: use glamor/inline instead
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: glamor@next
npm ERR! notarget Valid install targets:
npm ERR! notarget 3.0.0-3, 3.0.0-2, 3.0.0-1, 2.20.38, 2.20.37, 2.20.36, 2.20.35, 2.20.34, 2.20.33, 2.20.32, 2.20.31, 2.20.30, 2.20.29, 2.20.28, 2.20.27, 2.20.26, 2.20.25, 2.20.24, 2.20.23, 2.20.22, 2.20.21, 2.20.20, 2.20.19, 2.20.18, 2.20.17, 2.20.16, 2.20.15, 2.20.14, 2.20.13, 2.20.12, 2.20.10, 2.20.9, 2.20.8, 2.20.7, 2.20.6, 2.20.5, 2.20.4, 2.20.3, 2.20.2, 2.20.1, 2.20.0-alpha.2, 2.20.0-alpha.1, 2.19.0, 2.18.2, 2.18.1, 2.18.0, 2.17.16, 2.17.15, 2.17.14, 2.17.13, 2.17.12, 2.17.11, 2.17.10, 2.17.9, 2.17.8, 2.17.7, 2.17.6, 2.17.5, 2.17.4, 2.17.3, 2.17.2, 2.17.1, 2.17.0, 2.16.2, 2.16.1, 2.16.0, 2.15.6, 2.15.5, 2.15.4, 2.15.3, 2.15.2, 2.15.1, 2.15.0, 2.14.4, 2.14.3, 2.14.2, 2.14.1, 2.14.0, 2.13.0, 2.12.1, 2.12.0, 2.11.0, 2.10.0, 2.9.0, 2.8.0, 2.7.1, 2.7.0, 2.6.2, 2.6.1, 2.6.0, 2.5.0, 2.4.1, 2.4.0, 2.3.0, 2.2.7-alpha2, 2.2.7-alpha, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.0, 2.0.1
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'gatsby-plugin-glamor'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/delverichick/reasonml.github.io/npm-debug.log`

Any Suggestions @chenglou

**Comment by chidelmun** [comment]
`https://github.com/reasonml/reasonml.github.io/pull/69`

**Comment by chidelmun** [comment]
[PR here](https://github.com/reasonml/reasonml.github.io/pull/69)

**Comment by chenglou** [comment]
Done! Thanks =)
