### ISSUE TITLE
[doc] Installation instruction of bs-platform globally or locally is unclear

### ISSUE THREAD

**Issue by MoOx** [reasonml/reasonml.github.io#440]
In short, on Installation page of the doc we see:
- install bs-platform globally
- if new project bs -init...
- if existing project install bs-platform locally (?!)

That's confusing. Global install are good for local developer tools, not for projects.
If I have 2 projects that use different version of bs-platform, should I use global installs?
That's a question reason newbie could ask.

If we follow the doc as a new user, we are going to do a global install. Assuming we do that.
Now I do another project. The previous one ages. I update bs-platform (globally) for my most recent project. Major bump. Now I go back to my previous one. bs-platform won't be at the good version, config might breaks etc.

I think the doc should be clearer about this.

**Comment by kevinsimper** [comment]
Hi @MoOx 

Good question, I will always recommend to install it locally, but that does not give you a boilerplate functionality like installing it globally, so that is why there is two different advices.

I also wrote a blogpost about how to start a minimal reasonml project that you can see here: https://medium.com/@kevinsimper/how-to-start-a-minimal-reasonml-project-without-boilerplate-57e9e19bfa88

So first boilerplate project, if you want to get a quick start where there is less chance for error, install it globally. Once you know your way around, install it locally! :)

Hope it clears it up!
