### ISSUE TITLE
The 'Why' of 'What & Why' is vague and lacks evidence

### ISSUE THREAD

**Issue by Jazzyboy1** [reasonml/reasonml.github.io#729]
Context: https://reasonml.github.io/docs/en/what-and-why#why-use-reason

Reading that section as an already persuaded novice disciple of functional programming, I learn nothing new, and it seems to be a very general statement that applies equally to alternative functional-first languages. What does Reason bring to the table that alternatives don't or which is better than alternatives' offerings? 

Also; if I wasn't already persuaded of the merits of functional programming and strong typesystems, then I can't imagine the current brief paragraph being enough to persuade me. It's vague and doesn't offer any evidence for its claims. It might be helpful to provide a link to a case study.

**Comment by kyldvs** [comment]
Thanks for the issue! This section is intentionally brief so that the page does not become a novel explaining the values of functional programming. It's meant more of a reminder towards qualities that are beneficial in functional languages, and then if a reader is curious to learn more there are many articles talking about the benefits of these languages a quick search away. If you come across this page you likely already have a sense of the what & why of functional programming in general.

I do agree that we don't do a great job motivating why *Reason* over other functional programming languages. That's something we could try to improve here.
